server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:40000/postgres
    username: postgres
    password: postgres
  profiles:
    active: jwt-configuration

#logging:
#  level:
#    org:
#      springframework: DEBUG