server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:40000/postgres
    username: postgres
    password: postgres
  profiles:
    active: database-configuration

#logging:
#  level:
#    org:
#      springframework: DEBUG