spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.99.100:40000/postgres
  profiles:
    active: database-authentication
logging:
  level:
    org:
      springframework:
       web: debug